first:
  host: "www.mandar.com"
  filename: "templates/mandar.html"
second:
  host: "www.mandar1.com"
  filename: "templates/mandar1.html"
third:
  host: "www.mandar2.com"
  filename: "templates/mandar2.html"
